---
- hosts: exist
  tasks:
  - include_role:
      name: master
      tasks_from: register-join-command.yml

- hosts: scale
  tasks:
  - include_role:
      name: pre-ops
      tasks_from: set.yml
  - include_role:
      name: runtime/{{runtime}}
      tasks_from: install.yml
  - include_role:
      name: kubeadm-kubelet-kubectl
      tasks_from: install.yml
  - include_role:
      name: keepalived
      tasks_from: install-backup.yml
  - include_role:
      name: master
      tasks_from: join.yml