---
- hosts: scaledown
  gather_facts: no
  tasks:
  - include_role:
      name: master
      tasks_from: reset-and-delete.yml
  - include_role:
      name: kubeadm-kubelet-kubectl
      tasks_from: uninstall.yml
  - include_role:
      name: runtime/{{runtime}}
      tasks_from: uninstall.yml