---
- name: install kubelet and kubeadm
  tags: ["create-cluster", "scale-up-node"]
  yum:
    name: ["kubelet", "kubeadm"]
    state: present
    use_backend: yum

- name: uninstall kubelet and kubeadm
  tags: ["delete-cluster", "scale-down-node"]
  yum:
    name: ["kubelet", "kubeadm"]
    state: absent
    use_backend: yum
