---
- hosts: all
  roles:
  - role: pre-ops/set
  - role: docker/install
  - role: kubelet-kubeadm/install

- hosts: master
  roles:
  - role: kubectl/install
  - role: keepalived/install
    when: master_vip is defined
  - role: master/init
    when: inventory_hostname == groups.master[0]
  - role: master/getjoincommand
    when: inventory_hostname == groups.master[0]
  - role: master/join
    vars:
      kubeadm_join_master_command: "{{ hostvars[groups.master[0]].kubeadm_join_master_command }}" 
    when: inventory_hostname != groups.master[0]
    
- hosts: node
  roles:
  - role: node/join
    vars:
      kubeadm_join_node_command: "{{ hostvars[groups.master[0]].kubeadm_join_node_command }}" 

- hosts: master
  roles:
  - role: plugins
    when: inventory_hostname == groups.master[0]
