---
- hosts: scaledown
  gather_facts: no
  tasks:
  - include_role:
      name: pre-ops
      tasks_from: set.yml
  - include_role:
      name: runtime/{{runtime}}
      tasks_from: install.yml
  - include_role:
      name: kubeadm-kubelet-kubectl
      tasks_from: install.yml
  - include_role:
      name: keepalived
      tasks_from: install-backup.yml
  - include_role:
      name: master
      tasks_from: join.yml
    vars:
      control_plane_endpoint: "{{hostvars[groups.master[0]].control_plane_endpoint}}"
      certificate_key: "{{hostvars[groups.master[0]].certificate_key}}"
      token: "{{hostvars[groups.master[0]].token}}"
      ca_cert_hash: "{{hostvars[groups.master[0]].ca_cert_hash}}"