---
- name: set kernel arguments
  tags: ["create-cluster", "scale-up-node"]
  become: yes
  block:
  - name: copy k8s.conf to /etc/sysctl.conf.d/
    copy:
      src: k8s.conf
      dest: /etc/sysctl.d/
  - name: sysctl --system
    shell: |
      sysctl --system

- name: systemctl stop and disable firewalld
  tags: ["create-cluster", "scale-up-node"]
  become: yes
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: turn off selinux
  tags: ["create-cluster", "scale-up-node"]
  become: yes
  selinux:
    state: disabled  

- name: turn off swap
  tags: ["create-cluster", "scale-up-node"]
  become: yes
  block:
  - name: swapoff -a
    shell: |
      swapoff -a
  - name: remove swap lines in /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent  
    
