---
- name: set kernel arguments  
  become: yes
  block:
  - name: copy k8s.conf to /etc/sysctl.d/
    copy:
      src: k8s.conf
      dest: /etc/sysctl.d/
  - name: sysctl --system
    shell: |
      sysctl --system

- name: systemctl stop and disable firewalld
  become: yes
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: turn off selinux
  become: yes
  selinux:
    state: disabled  

- name: turn off swap
  become: yes
  block:
  - name: swapoff -a
    shell: |
      swapoff -a
  - name: remove swap lines in /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent  
    
- name: <获取主机操作系统、CPU架构等信息>
  setup:
    gather_subset:
    - min