---
- name: <拷贝kubernetes的repo文件到/etc/yum.repos.d/>
  template:
    src: centos/aliyun-kubernetes.repo.j2
    dest: /etc/yum.repos.d/aliyun-kubernetes.repo
    force: yes

- name: <拷贝centos的repo文件到/etc/yum.repos.d/>
  copy:
    src: centos/aliyun-base.repo
    dest: /etc/yum.repos.d/aliyun-base.repo
    force: yes

- name: <调用yum模块进行安装>
  yum: 
    name: kubelet-{{kubernetes_version}},kubectl-{{kubernetes_version}},kubeadm-{{kubernetes_version}}
    state: present
    disablerepo: "*"
    enablerepo: "aliyun-*"
    
- name: <启动kubelet>
  service:
    name: kubelet
    state: started
    enabled: yes


