---
- name: <拷贝kubeadm-join-node.yml文件>
  become: yes
  template:
    src: "v{{kubernetes_major_version}}/kubeadm-join-node.yml.j2"
    dest: /etc/kubernetes/kubeadm-join-node.yml
    force: yes
    mode: 0644

- name: <执行kubeadm join命令以添加节点>
  become: yes
  command: kubeadm join --config /etc/kubernetes/kubeadm-join-node.yml
