- name: <拷贝kubeadm-join-node.yml文件>
  become: yes
  template:
    src: "v{{kubernetes_major_version}}/kubeadm-join-node.yml.j2
    dest: /etc/kubernetes
    force: yes

- name: <执行kubeadm join命令以添加节点>
  become: yes
  command: kubeadm join --config /etc/kubernetes/kubeadm-join-node.yml
  
- name: <创建~/.kube目录>
  file:
    path: "~/.kube"
    state: directory
    mode: 0755
    
- name: <拷贝kubeconfig文件到用户目录下>  
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "~/.kube/config"
    force: yes
    remote_src: yes
    group: "{{ansible_user}}"
    owner: "{{ansible_user}}"
    mode: 0644