---
- name: <拷贝kubeadm-init-master.yml配置文件>
  become: yes
  template:
    src: "v{{kubernetes_major_version}}/kubeadm-init-master.yml.j2"
    dest: /etc/kubernetes/kubeadm-init-master.yml
    force: yes
    mode: 0644

- name: <执行kubeadm init命令>
  become: yes
  command: kubeadm init --config /etc/kubernetes/kubeadm-init-master.yml

- name: <chmod of /etc/kubernetes/admin.conf>
  ignore_errors: yes
  become: yes
  file:
    path: /etc/kubernetes/admin.conf
    state: file
    mode: 0644

- name: <去掉Master的taint>
  ignore_errors: yes
  command: kubectl taint node {{node_name}} node-role.kubernetes.io/master- --kubeconfig /etc/kubernetes/admin.conf  

- name: <创建~/.kube目录>
  ignore_errors: yes
  file:
    path: "~/.kube"
    state: directory
    mode: 0755

- name: <拷贝kubeconfig文件到用户目录下>  
  ignore_errors: yes
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "~/.kube/config"
    force: yes
    remote_src: yes
    group: "{{ansible_user}}"
    owner: "{{ansible_user}}"
    mode: 0644

  