---
- name: 拷贝kubeadm-init.yml配置文件
  template:
    src: kubeadm-init.yml.j2
    dest: /etc/kubernetes
    force: yes

- name: 执行kubeadm init命令
  command: kubeadm init --config /etc/kubernetes/kubeadm-init.yml

  