---
- name: <拷贝kubeadm-init-master.yml配置文件>
  become: yes
  template:
    src: "v{{kubernetes_major_version}}/kubeadm-init-master.yml.j2"
    dest: /etc/kubernetes/kubeadm-init-master.yml
    force: yes

- name: <执行kubeadm init命令>
  become: yes
  command: kubeadm init --config /etc/kubernetes/kubeadm-init-master.yml

- name: <拷贝kubeconfig文件到用户目录下>  
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "~/.kube/config"
    force: yes
    remote_src: yes
    group: "{{ansible_user}}"
    owner: "{{ansible_user}}"
    mode: 0644

  