---
- name: install docker
  tags: ["create-cluster", "scale-up-node"]
  become: yes
  block:
  - name: yum install docker
    yum:
      name: docker-ce
      state: present
      use_backend: yum
  - name: mkdir /etc/docker
    file:
      path: /etc/docker
      state: directory
  - name: copy and configure daemon.json
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
  - name: systemctl start and enable docker
    service: 
      name: docker
      state: started
      enabled: yes

- name: uninstall docker
  tags: ["delete-cluster", "scale-down-node"]
  become: yes
  block:
  - name: systemctl stop and disable docker
    service:
      name: docker
      state: stopped
      enabled: no
  - name: remove /etc/docker/daemon.json
    file:
      path: /etc/docker/daemon.json
      state: absent
  - name: yum remove docker-ce docker-ce-cli
    yum:
      name: ["docker-ce", "docker-ce-cli"]
      state: absent
      use_backend: yum
