---
- name: <拷贝kubeadm-config.yaml文件>
  template:
    src: kubeadm-config.yaml.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
- name: <执行kubeadm init命令>
  shell: |
    kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --node-name {{ inventory_hostname }}
  
