---
- name: <拷贝centos的repo文件到/etc/yum.repos.d/>
  become: yes
  copy:
    src: centos/aliyun-base.repo
    dest: /etc/yum.repos.d/aliyun-base.repo
    force: yes

- name: <拷贝docker的repo文件到/etc/yum.repos.d/>
  become: yes
  template:
    src: aliyun-docker.repo.j2
    dest: /etc/yum.repos.d/aliyun-docker.repo
    force: yes

- name: <yum安装docker>
  become: yes
  yum:
    name: "docker-ce-{{docker_version}},docker-ce-cli-{{docker_version}}"
    state: present
    disablerepo: "*"
    enablerepo: "aliyun-*"

- name: <创建/etc/docker目录>
  become: yes
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: <拷贝daemon.json>
  become: yes
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    force: yes

- name: <启动docker>
  service: 
    name: docker
    state: started
    enabled: yes